version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "dependabot"
    # Limit the number of open pull requests
    open-pull-requests-limit: 10
    # Set version update strategy
    versioning-strategy: auto
    # Specify commit message conventions
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope" 